# Generated by Django 5.2.1 on 2025-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author Name')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='Profile URL')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.AddField(
            model_name='source',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Source ID (from API)'),
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Source URL'),
        ),
    ]
