# Generated by Django 5.2.1 on 2025-05-21 09:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_author_source_source_id_source_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Full Content')),
                ('url', models.URLField(unique=True, verbose_name='Article URL')),
                ('url_to_image', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('published_at', models.DateTimeField(verbose_name='Published At')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fetched At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.author', verbose_name='Author')),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='core.category', verbose_name='Categories')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.countries', verbose_name='Country')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
