# Generated by Django 5.2.1 on 2025-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='url_to_image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Image URL'),
        ),
    ]
