# Generated by Django 5.2.1 on 2025-05-21 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_url_to_image'),
        ('core', '0003_author_source_source_id_source_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('category_preferences', models.ManyToManyField(blank=True, related_name='category_preferences', to='core.category', verbose_name='Category Preferences')),
                ('country_preferences', models.ManyToManyField(blank=True, related_name='country_preferences', to='core.countries', verbose_name='Country Preferences')),
                ('source_preferences', models.ManyToManyField(blank=True, related_name='source_preferences', to='core.source', verbose_name='Source Preferences')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-id'],
            },
        ),
    ]
