# Generated by Django 5.2.1 on 2025-05-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_created_at_article_updated_at_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
